import type { MutualFundData } from "./types"

export const sampleData: MutualFundData[] = [
  {
    id: "fund-1",
    name: "HDFC Top 100 Fund",
    category: "Large Cap",
    aum: 21456.78,
    nav: 823.45,
    expenseRatio: 1.25,
    oneYearReturn: 18.7,
    threeYearReturn: 12.5,
    fiveYearReturn: 15.2,
    riskLevel: "Moderate",
    sectors: [
      { name: "Financial", allocation: 32 },
      { name: "Technology", allocation: 18 },
      { name: "Energy", allocation: 15 },
      { name: "Consumer", allocation: 12 },
      { name: "Healthcare", allocation: 10 },
      { name: "Others", allocation: 13 },
    ],
    inceptionDate: "2000-10-11",
    fundManager: "Prashant Jain",
    benchmark: "Nifty 100",
  },
  {
    id: "fund-2",
    name: "SBI Small Cap Fund",
    category: "Small Cap",
    aum: 12345.67,
    nav: 112.34,
    expenseRatio: 1.78,
    oneYearReturn: 22.4,
    threeYearReturn: 15.8,
    fiveYearReturn: 18.9,
    riskLevel: "High",
    sectors: [
      { name: "Industrial", allocation: 28 },
      { name: "Consumer", allocation: 22 },
      { name: "Financial", allocation: 18 },
      { name: "Technology", allocation: 12 },
      { name: "Materials", allocation: 10 },
      { name: "Others", allocation: 10 },
    ],
    inceptionDate: "2009-09-22",
    fundManager: "R. Srinivasan",
    benchmark: "Nifty Smallcap 250",
  },
  {
    id: "fund-3",
    name: "Axis Bluechip Fund",
    category: "Large Cap",
    aum: 18765.43,
    nav: 456.78,
    expenseRatio: 1.05,
    oneYearReturn: 16.2,
    threeYearReturn: 11.7,
    fiveYearReturn: 14.3,
    riskLevel: "Moderate",
    sectors: [
      { name: "Financial", allocation: 30 },
      { name: "Technology", allocation: 25 },
      { name: "Consumer", allocation: 15 },
      { name: "Healthcare", allocation: 12 },
      { name: "Energy", allocation: 8 },
      { name: "Others", allocation: 10 },
    ],
    inceptionDate: "2009-01-05",
    fundManager: "Shreyash Devalkar",
    benchmark: "Nifty 50",
  },
  {
    id: "fund-4",
    name: "Mirae Asset Emerging Bluechip",
    category: "Mid Cap",
    aum: 24567.89,
    nav: 98.76,
    expenseRatio: 1.45,
    oneYearReturn: 24.8,
    threeYearReturn: 16.9,
    fiveYearReturn: 19.7,
    riskLevel: "High",
    sectors: [
      { name: "Financial", allocation: 25 },
      { name: "Consumer", allocation: 20 },
      { name: "Industrial", allocation: 18 },
      { name: "Technology", allocation: 15 },
      { name: "Healthcare", allocation: 12 },
      { name: "Others", allocation: 10 },
    ],
    inceptionDate: "2010-07-09",
    fundManager: "Neelesh Surana",
    benchmark: "Nifty Midcap 150",
  },
  {
    id: "fund-5",
    name: "ICICI Prudential Value Discovery",
    category: "Value",
    aum: 15678.9,
    nav: 345.67,
    expenseRatio: 1.35,
    oneYearReturn: 14.5,
    threeYearReturn: 10.2,
    fiveYearReturn: 13.8,
    riskLevel: "Moderate",
    sectors: [
      { name: "Financial", allocation: 28 },
      { name: "Energy", allocation: 18 },
      { name: "Materials", allocation: 15 },
      { name: "Consumer", allocation: 14 },
      { name: "Industrial", allocation: 12 },
      { name: "Others", allocation: 13 },
    ],
    inceptionDate: "2004-08-16",
    fundManager: "Sankaran Naren",
    benchmark: "Nifty 500",
  },
  {
    id: "fund-6",
    name: "Parag Parikh Flexi Cap Fund",
    category: "Flexi Cap",
    aum: 9876.54,
    nav: 54.32,
    expenseRatio: 1.15,
    oneYearReturn: 19.3,
    threeYearReturn: 14.7,
    fiveYearReturn: 17.2,
    riskLevel: "Moderate",
    sectors: [
      { name: "Technology", allocation: 30 },
      { name: "Financial", allocation: 22 },
      { name: "Consumer", allocation: 18 },
      { name: "Healthcare", allocation: 15 },
      { name: "Industrial", allocation: 10 },
      { name: "Others", allocation: 5 },
    ],
    inceptionDate: "2013-05-24",
    fundManager: "Rajeev Thakkar",
    benchmark: "Nifty 500",
  },
  {
    id: "fund-7",
    name: "Kotak Emerging Equity Fund",
    category: "Mid Cap",
    aum: 14532.1,
    nav: 78.9,
    expenseRatio: 1.55,
    oneYearReturn: 21.6,
    threeYearReturn: 15.3,
    fiveYearReturn: 18.1,
    riskLevel: "High",
    sectors: [
      { name: "Financial", allocation: 26 },
      { name: "Industrial", allocation: 22 },
      { name: "Consumer", allocation: 18 },
      { name: "Technology", allocation: 14 },
      { name: "Materials", allocation: 12 },
      { name: "Others", allocation: 8 },
    ],
    inceptionDate: "2007-03-30",
    fundManager: "Pankaj Tibrewal",
    benchmark: "Nifty Midcap 150",
  },
  {
    id: "fund-8",
    name: "Aditya Birla Sun Life Tax Relief 96",
    category: "ELSS",
    aum: 8765.43,
    nav: 123.45,
    expenseRatio: 1.65,
    oneYearReturn: 17.8,
    threeYearReturn: 12.9,
    fiveYearReturn: 15.7,
    riskLevel: "Moderate",
    sectors: [
      { name: "Financial", allocation: 29 },
      { name: "Technology", allocation: 20 },
      { name: "Consumer", allocation: 16 },
      { name: "Healthcare", allocation: 14 },
      { name: "Industrial", allocation: 12 },
      { name: "Others", allocation: 9 },
    ],
    inceptionDate: "1996-03-29",
    fundManager: "Satyabrata Mohanty",
    benchmark: "Nifty 500",
  },
  {
    id: "fund-9",
    name: "DSP Midcap Fund",
    category: "Mid Cap",
    aum: 13579.24,
    nav: 87.65,
    expenseRatio: 1.48,
    oneYearReturn: 20.4,
    threeYearReturn: 14.8,
    fiveYearReturn: 17.5,
    riskLevel: "High",
    sectors: [
      { name: "Financial", allocation: 24 },
      { name: "Consumer", allocation: 22 },
      { name: "Industrial", allocation: 20 },
      { name: "Healthcare", allocation: 15 },
      { name: "Technology", allocation: 12 },
      { name: "Others", allocation: 7 },
    ],
    inceptionDate: "2006-11-14",
    fundManager: "Vinit Sambre",
    benchmark: "Nifty Midcap 150",
  },
  {
    id: "fund-10",
    name: "Nippon India Pharma Fund",
    category: "Sectoral",
    aum: 5432.1,
    nav: 234.56,
    expenseRatio: 1.85,
    oneYearReturn: -5.2,
    threeYearReturn: 8.7,
    fiveYearReturn: 12.3,
    riskLevel: "High",
    sectors: [
      { name: "Healthcare", allocation: 92 },
      { name: "Others", allocation: 8 },
    ],
    inceptionDate: "2004-06-05",
    fundManager: "Sailesh Raj Bhan",
    benchmark: "Nifty Pharma",
  },
]
